config/routes.rb
Rails.application.routes.draw do
  resources :sections

  resources :course_sections
  resources :course_groups
  resources :lectures
  resources :periods

  resources :rooms do
    collection do
      get :importer
      post :import
    end
  end

  resources :lecturers do
    collection do
      get :importer
      get :random
      post :import
    end
  end

  resources :courses do
    collection do
      get :importer
      post :import
    end
  end

  resources :schedules

  get '/resources', :to => 'resources#index', :as => 'resources'
  get '/resources/sync', :to => 'resources#sync', :as => 'resources_sync'
  post '/resources/run_sync', :to => 'resources#run_sync', :as => 'resources_run_sync'

  # root path
  root 'home#index'
end

app/models/lecture.rb
# == Schema Information
#
# Table name: lectures
#
#  id                :integer          not null, primary key
#  course_section_id :integer
#  room_id           :integer
#  start_period_id   :integer
#  end_period_id     :integer
#  schedule_id       :integer
#  created_at        :datetime
#  updated_at        :datetime
#

class Lecture < ActiveRecord::Base

  belongs_to :course_section
  belongs_to :room

  belongs_to :start_period, class_name: 'Period', foreign_key: 'start_period_id'
  belongs_to :end_period, class_name: 'Period', foreign_key: 'end_period_id'

  belongs_to :schedule

  def duration
    (end_period.time_slot - start_period.time_slot) + 1
  end

end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_lecture, only: [:show, :edit, :update, :destroy]

  # GET /lectures
  # GET /lectures.json
  def index
    @lectures = Lecture.all
  end

  # GET /lectures/1
  # GET /lectures/1.json
  def show
  end

  # GET /lectures/new
  def new
    @lecture = Lecture.new
  end

  # GET /lectures/1/edit
  def edit
  end

  # POST /lectures
  # POST /lectures.json
  def create
    @lecture = Lecture.new(lecture_params)

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to @lecture, notice: 'Lecture was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lecture }
      else
        format.html { render action: 'new' }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lectures/1
  # PATCH/PUT /lectures/1.json
  def update
    respond_to do |format|
      if @lecture.update(lecture_params)
        format.html { redirect_to @lecture, notice: 'Lecture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1
  # DELETE /lectures/1.json
  def destroy
    @lecture.destroy
    respond_to do |format|
      format.html { redirect_to lectures_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
      @lecture = Lecture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lecture_params
      params[:lecture]
    end
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_form.html.erb
<%= form_for(@lecture) do |f| %>
  <% if @lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% @lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lectures/edit.html.erb
<h1>Editing lecture</h1>

<%= render 'form' %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

app/views/lectures/index.html.erb
<h1>Listing lectures</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= link_to 'Show', lecture %></td>
        <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lecture', new_lecture_path %>

app/views/lectures/new.html.erb
<h1>New lecture</h1>

<%= render 'form' %>

<%= link_to 'Back', lectures_path %>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_lecture_path(@lecture) %> |
<%= link_to 'Back', lectures_path %>