config/routes.rb
Rails.application.routes.draw do
  resources :sections

  resources :course_sections
  resources :course_groups
  resources :lectures
  resources :periods

  resources :rooms do
    collection do
      get :importer
      post :import
    end
  end

  resources :lecturers do
    collection do
      get :importer
      get :random
      post :import
    end
  end

  resources :courses do
    collection do
      get :importer
      post :import
    end
  end

  resources :schedules

  get '/resources', :to => 'resources#index', :as => 'resources'
  get '/resources/sync', :to => 'resources#sync', :as => 'resources_sync'
  post '/resources/run_sync', :to => 'resources#run_sync', :as => 'resources_run_sync'

  # root path
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @schedules = Schedule.all
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% content_for :content do %>

    <div class="row">
      <div class="span8">
        <div class="m-t-10">
          <% if @schedules.present? %>
          <% else %>
              <strong>No schedules found.</strong>
          <% end %>
        </div>
      </div>
      <!--<div class="span4">-->
        <!--<ul class="nav nav-tabs nav-stacked">-->
          <!--<li>-->
            <!--<%= link_to new_schedule_path do %>-->
                <!--<i class="icon-calendar"></i>-->
                <!--Create A New Schedule-->
            <!--<% end %>-->
          <!--</li>-->
          <!--<li>-->
            <!--<%= link_to new_lecturer_path do %>-->
                <!--<i class="icon-user"></i>-->
                <!--Add A Lecturer-->
            <!--<% end %>-->
          <!--</li>-->
          <!--<li>-->
            <!--<%= link_to new_course_path do %>-->
                <!--<i class="icon-book"></i>-->
                <!--Add A Course-->
            <!--<% end %>-->
          <!--</li>-->
          <!--<li>-->
            <!--<%= link_to new_room_path do %>-->
                <!--<i class="icon-sign-blank"></i>-->
                <!--Create A New Room-->
            <!--<% end %>-->
          <!--</li>-->
        <!--</ul>-->
      <!--</div>-->
    </div>

<% end %>