config/routes.rb
Rails.application.routes.draw do
  resources :sections

  resources :course_sections
  resources :course_groups
  resources :lectures
  resources :periods

  resources :rooms do
    collection do
      get :importer
      post :import
    end
  end

  resources :lecturers do
    collection do
      get :importer
      get :random
      post :import
    end
  end

  resources :courses do
    collection do
      get :importer
      post :import
    end
  end

  resources :schedules

  get '/resources', :to => 'resources#index', :as => 'resources'
  get '/resources/sync', :to => 'resources#sync', :as => 'resources_sync'
  post '/resources/run_sync', :to => 'resources#run_sync', :as => 'resources_run_sync'

  # root path
  root 'home#index'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = Course.all
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  def importer
  end

  def import
    file = params[:file]
    if ['.xls', '.xlsx'].include? File.extname(file.original_filename)
      course_groups = CourseGroup.all.to_a

      wb = open_spreadsheet file
      wb.default_sheet = wb.sheets.third
      6.upto wb.last_row do |row|
        code = wb.row(row)[1]
        name = wb.row(row)[2]
        if code.present? and name.present?
          begin
            Course.create({code: code, name: name, occurrence: 3, duration: 1.0, course_group_id: course_groups.sample.id})
          rescue StandardError => e
            puts e
          end
        end
      end

      success_message 'Courses imported successfully'
    else
      error_message 'Invalid file type. Please upload a .xls or .xlsx file type'
    end

    redirect_to courses_path
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params[:course]
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for :course, class: 'form-horizontal form-validate' do |f| %>
  <% if @course.present? and @course.errors.any? %>
    <div id="alert alert-danger">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/importer.html.erb
<% content_for :masthead do %>
    <h2>Courses</h2>

    <p>The importer allows you to bulk create courses from an excel file.</p>
<% end %>

<% content_for :content do %>
    <form action="<%= import_courses_path %>" method="post" enctype="multipart/form-data" class="form-horizontal form-validate">
      <%= hidden_field_tag(request_forgery_protection_token.to_s, form_authenticity_token) %>
      <fieldset>
        <div class="control-group">
          <label class="control-label" for="name">Excel File</label>
          <div class="controls">
            <input type="file" class="input-large required" name="file" id="file">
          </div>
        </div>

        <div class="form-actions bg-transparent">
          <button type="submit" class="btn btn-primary">Import</button>
        </div>
      </fieldset>
    </form>
<% end %>

app/views/courses/index.html.erb
<% content_for :masthead do %>
    <h2>Courses</h2>

    <p>You are currently have <%= @courses.count %> courses
      created. <%= link_to "Click here", new_course_path %> to create a new one.</p>
<% end %>

<% content_for :content do %>

    <div class="row-fluid">
      <div class="span8">
        <div class="m-t-10">
          <% if @courses.present? %>

              <script type="text/javascript">
                $(function(){
                    $('#courseList').dataTable();
                });
              </script>

              <table id="courseList" class="table table-bordered table-strped table-condensed">
                <thead>
                <tr>
                  <th>Name</th>
                  <th>Code</th>
                  <th>Occurrence</th>
                  <th>Duration</th>
                </tr>
                </thead>
                <tbody>
                <% @courses.each do |c| %>
                    <tr>
                      <td><%= c.name %></td>
                      <td><%= c.code %></td>
                      <td><%= c.occurrence %> (per week)</td>
                      <td><%= c.duration %> hour(s)</td>
                    </tr>
                <% end %>
                </tbody>
              </table>
          <% else %>
              <strong>No courses found.</strong>
          <% end %>
        </div>
      </div>
      <div class="span4">
        <ul class="nav nav-tabs nav-stacked">
          <li>
            <%= link_to new_course_path do %>
                <i class="icon-book"></i>
                Add A Course
            <% end %>
          </li>
          <li>
            <%= link_to importer_courses_path do %>
                <i class="icon-upload-alt"></i>
                Import Courses
            <% end %>
          </li>
        </ul>
      </div>
    </div>

<% end %>

app/views/courses/new.html.erb
<% content_for :masthead do %>
    <h2>Courses</h2>

    <p></p>
<% end %>

<% content_for :content do %>

    <%= render partial: 'form' %>

<% end %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>