config/routes.rb
Rails.application.routes.draw do
  resources :sections

  resources :course_sections
  resources :course_groups
  resources :lectures
  resources :periods

  resources :rooms do
    collection do
      get :importer
      post :import
    end
  end

  resources :lecturers do
    collection do
      get :importer
      get :random
      post :import
    end
  end

  resources :courses do
    collection do
      get :importer
      post :import
    end
  end

  resources :schedules

  get '/resources', :to => 'resources#index', :as => 'resources'
  get '/resources/sync', :to => 'resources#sync', :as => 'resources_sync'
  post '/resources/run_sync', :to => 'resources#run_sync', :as => 'resources_run_sync'

  # root path
  root 'home#index'
end

app/models/course_section.rb
# == Schema Information
#
# Table name: course_sections
#
#  id                       :integer          not null, primary key
#  periods                  :integer
#  slot_lock_index          :integer
#  day_lock_index           :integer
#  course_id                :integer
#  section_id               :integer
#  lecturer_id              :integer
#  linked_course_section_id :integer
#  created_at               :datetime
#  updated_at               :datetime
#

class CourseSection < ActiveRecord::Base

  belongs_to :course
  belongs_to :section
  belongs_to :lecturer

  has_many :lectures

  belongs_to :linked_course_section, :class_name => "CourseSection", :foreign_key => "linked_course_section_id"
  has_many :linked_course_sections, :class_name => "CourseSection",:foreign_key => "linked_course_section_id"

  validates :course_id, presence: true, :uniqueness => {scope: :section_id}
  validates :section_id, presence: true, :uniqueness => {scope: :course_id}

end

app/controllers/course_sections_controller.rb
class CourseSectionsController < ApplicationController
  before_action :set_course_section, only: [:show, :edit, :update, :destroy]

  def index
    @course_sections = CourseSection.all
  end

  def show
  end

  def new
    @course_section = CourseSection.new
  end

  def edit
  end

  def create
    @course_section = CourseSection.new(course_section_params)

    respond_to do |format|
      if @course_section.save
        format.html { redirect_to @course_section, notice: 'Course section was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course_section }
      else
        format.html { render action: 'new' }
        format.json { render json: @course_section.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @course_section.update(course_section_params)
        format.html { redirect_to @course_section, notice: 'Course section was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course_section.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @course_section.destroy
    respond_to do |format|
      format.html { redirect_to course_sections_url }
      format.json { head :no_content }
    end
  end

  private

  def set_course_section
    @course_section = CourseSection.find(params[:id])
  end

  def course_section_params
    params[:course_section]
  end
end

app/helpers/course_sections_helper.rb
module CourseSectionsHelper
end

app/views/course_sections/_form.html.erb
<%= form_for(@course_section) do |f| %>
  <% if @course_section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course_section.errors.count, "error") %> prohibited this course_section from being saved:</h2>

      <ul>
      <% @course_section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/course_sections/edit.html.erb
<h1>Editing course_section</h1>

<%= render 'form' %>

<%= link_to 'Show', @course_section %> |
<%= link_to 'Back', course_sections_path %>

app/views/course_sections/index.html.erb
<h1>Listing course_sections</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @course_sections.each do |course_section| %>
      <tr>
        <td><%= link_to 'Show', course_section %></td>
        <td><%= link_to 'Edit', edit_course_section_path(course_section) %></td>
        <td><%= link_to 'Destroy', course_section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course section', new_course_section_path %>

app/views/course_sections/new.html.erb
<h1>New course_section</h1>

<%= render 'form' %>

<%= link_to 'Back', course_sections_path %>

app/views/course_sections/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_course_section_path(@course_section) %> |
<%= link_to 'Back', course_sections_path %>